/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData speech_bubble = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData food = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData heart_empty = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData heart_1 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData heart_empty_1 = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData heart_2 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData heart_filled = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData heart_3 = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData heart_empty_2 = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData heart_4 = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData heart_empty_3 = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData mode_comment = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData comment_1 = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData comment_2 = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData comment_3 = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData plate_fork_and_knife = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData heart__1_ = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData likee = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData fast_food = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData share__1_ = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData dinner = const IconData(0xe847, fontFamily: _kFontFam);
}
